### ISSUE TITLE
Problem: Cannot make POST request to create new entity

### ISSUE THREAD

**Issue by Drast10** [Codaisseur/fullstack-labs#4] opened 2019-05-29 13:09 UTC
Summary:
When I try to send a POST request to my API to add a new entity into the database, it says "Cannot POST".

Steps:
1. Create a Sequelize model for the entity.
1. Defined a POST route to add new entities.
1. Sent a POST request to the route with Postman including a body with all the required fields.

Expected result:
The server replies that the entity is now in the database, and it appears in the table.

Actual result:
It shows an error that it cannot post to that route.

Relevant logs and errors:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot POST /products</pre>
    </body>
</html>
```

**Comment by davidystephenson** [comment] 2019-05-29 13:28
After some investigation, we concluded this is actually a duplicate of #2  The error was not appearing due to the server not being restarted at the right time. Adding `module.exports = router` at the bottom of `routes.js` fixed it.

**Closed as completed** 2019-05-29 13:28 UTC
